/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as LessonLessonIdIndexRouteImport } from './routes/lesson.$lessonId.index'
import { Route as LessonLessonIdStepIdRouteImport } from './routes/lesson.$lessonId.$stepId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdIndexRoute = LessonLessonIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LessonLessonIdRoute,
} as any)
const LessonLessonIdStepIdRoute = LessonLessonIdStepIdRouteImport.update({
  id: '/$stepId',
  path: '/$stepId',
  getParentRoute: () => LessonLessonIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lesson/$lessonId': typeof LessonLessonIdRouteWithChildren
  '/lesson/$lessonId/$stepId': typeof LessonLessonIdStepIdRoute
  '/lesson/$lessonId/': typeof LessonLessonIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lesson/$lessonId/$stepId': typeof LessonLessonIdStepIdRoute
  '/lesson/$lessonId': typeof LessonLessonIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lesson/$lessonId': typeof LessonLessonIdRouteWithChildren
  '/lesson/$lessonId/$stepId': typeof LessonLessonIdStepIdRoute
  '/lesson/$lessonId/': typeof LessonLessonIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lesson/$lessonId'
    | '/lesson/$lessonId/$stepId'
    | '/lesson/$lessonId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lesson/$lessonId/$stepId' | '/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/lesson/$lessonId'
    | '/lesson/$lessonId/$stepId'
    | '/lesson/$lessonId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LessonLessonIdRoute: typeof LessonLessonIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId/': {
      id: '/lesson/$lessonId/'
      path: '/'
      fullPath: '/lesson/$lessonId/'
      preLoaderRoute: typeof LessonLessonIdIndexRouteImport
      parentRoute: typeof LessonLessonIdRoute
    }
    '/lesson/$lessonId/$stepId': {
      id: '/lesson/$lessonId/$stepId'
      path: '/$stepId'
      fullPath: '/lesson/$lessonId/$stepId'
      preLoaderRoute: typeof LessonLessonIdStepIdRouteImport
      parentRoute: typeof LessonLessonIdRoute
    }
  }
}

interface LessonLessonIdRouteChildren {
  LessonLessonIdStepIdRoute: typeof LessonLessonIdStepIdRoute
  LessonLessonIdIndexRoute: typeof LessonLessonIdIndexRoute
}

const LessonLessonIdRouteChildren: LessonLessonIdRouteChildren = {
  LessonLessonIdStepIdRoute: LessonLessonIdStepIdRoute,
  LessonLessonIdIndexRoute: LessonLessonIdIndexRoute,
}

const LessonLessonIdRouteWithChildren = LessonLessonIdRoute._addFileChildren(
  LessonLessonIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LessonLessonIdRoute: LessonLessonIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
